[pytest]
# Configura a URL base da API para o pacote requests (opcional, mas boa prática)
base_url = https://compassuol.serverest.dev

# Define os padrões de nomes de arquivos e funções de teste
python_files = test_*.py
python_functions = test_*

# Registra marcadores customizados se quiser filtrar testes depois (ex: pytest -m contract)
markers =
    smoke: Testes rápidos de caminhos felizes
    regressao: Testes de regressão completos